apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: stepheng323/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: stepheng323/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: stepheng323/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: stepheng323/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: stepheng323/payment
      context: payment
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
